### ISSUE TITLE
Note that the current version of the module murders the installation of freescout version 1.8.71

### ISSUE THREAD

**Issue by mchuc** [avenjamin/freescout-UnassignedCount-Module#1]
I installed this add-on today, and it made all the frescout free;

nothing could be done
fortunately, I found in the logs that at line 69 in the file 
freescout-UnassignedCount-Module/Providers/UnassignedCountServiceProvider.php

getFolderByType(1)->getCount();
causes an error to be thrown, so I manually replaced it with 0 and saved the installation;

can't try/catch be added there?

**Comment by avenjamin** [comment]
Thanks @mchuc. I'll have a look at this tonight and fix it.

**Comment by avenjamin** [comment]
@mchuc do you happen to have the error message/stack trace still in your log files?
